FROM golang:1.19-alpine AS build

WORKDIR /app

COPY . .

RUN go mod download
RUN CGO_ENABLED=0 go build -o producer ./cmd/producer/

FROM alpine:latest

WORKDIR /app

COPY --from=build /app/producer /app/

CMD ["/app/producer"]