CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE IF NOT EXISTS MESSAGES(
    ID UUID DEFAULT uuid_generate_v4() PRIMARY KEY,
    HEADER VARCHAR(100) NOT NULL,
    CONTENT VARCHAR(500) NOT NULL
);